### ISSUE TITLE
Build successful, exception when running

### ISSUE THREAD

**Issue by ilMike42** [TachiWeb/TachiWeb-Server#5]
When I try to run the server, I get this exception

ilmike@mymachine:~/TachiWeb-Server/target$ java -jar TachiServer-1.0-SNAPSHOT-jar-with-dependencies.jar
[main] INFO xyz.nulldev.ts.TachiServer - Starting server...
Exception in thread "main" java.lang.VerifyError: class xyz.nulldev.ts.android.CustomContext overrides final method getString.(I[Ljava/lang/Object;)Ljava/lang/String;
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
at java.lang.Class.getGenericSuperclass(Class.java:777)
at uy.kohesive.injekt.api.FullTypeReference.(TypeInfo.kt:34)
at xyz.nulldev.ts.ServerModule$registerInjectables$$inlined$addSingletonFactory$1.(TypeInfo.kt:27)
at xyz.nulldev.ts.ServerModule.registerInjectables(ServerModule.kt:70)
at uy.kohesive.injekt.api.InjektModule$DefaultImpls.registerWith(Modules.kt:18)
at xyz.nulldev.ts.ServerModule.registerWith(ServerModule.kt:41)
at uy.kohesive.injekt.api.InjektRegistrar$DefaultImpls.importModule(Registrar.kt:5)
at uy.kohesive.injekt.registry.default.DefaultRegistrar.importModule(DefaultRegistrar.kt:13)
at uy.kohesive.injekt.api.InjektScope.importModule(Scope.kt)
at xyz.nulldev.ts.TachiServer.main(TachiServer.kt:56)

**Comment by null-dev** [comment]
This code in this repo is actually severely out of date! I have an up to date version of the code in another repo here: https://github.com/null-dev/TW-Compat.

The build instructions for that version are here: https://github.com/null-dev/TW-Compat/blob/master/INSTALL.md

I have these two repositories separate like this because I'm still shuffling around the git submodules and I'd rather not mess up the git history of the main branch.

**Comment by ilMike42** [comment]
Thanks man!
